#ifndef _TYPES_HELIOS_H_
#define _TYPES_HELIOS_H_

#include <stdint.h>




#define  HELIOS_MAX_REG_ADDR  0x83D00000
#define  HELIOS_MIN_REG_ADDR  0x83C00000


#define  HELIOS_FRAME_FLAG                0x55AA2552  // helios

#define HELIOS_NET_CMD_BEGIN                   0x000
#define HELIOS_NET_CMD_READ_REGISTER           0x001
#define HELIOS_NET_CMD_WRITE_REGISTER          0x002
#define HELIOS_NET_CMD_TOP_BIN_UPDATE          0x003
#define HELIOS_NET_CMD_TOPBACKUP_UPDATE        0x004
#define HELIOS_NET_CMD_BOT_BIN_UPDATE          0x005
#define HELIOS_NET_CMD_BOTBACKUP_UPDATE        0x006
#define HELIOS_NET_CMD_LINUX_APP_UPDATE			0x007
#define HELIOS_NET_CMD_LAPPBACKUP_UPDATE		0x008
#define HELIOS_NET_CMD_READ_CONFIG          	0x009
#define HELIOS_NET_CMD_WRITE_CONFIG				0x00A
#define HELIOS_NET_CMD_TOP_PARA_UPDATE			0x00B
#define HELIOS_NET_CMD_BOT_PARA_UPDATE			0x00C
#define HELIOS_NET_CMD_TOP_FLASH_READ			0x00D
#define HELIOS_NET_CMD_TOP_FLASH_WRITE			0x00E
#define HELIOS_NET_CMD_TOP_READ_REGISTER		0x00F
#define HELIOS_NET_CMD_TOP_WRITE_REGISTER		0x010
#define HELIOS_NET_CMD_TOP_GET_INTENSITY		0x011
#define HELIOS_NET_CMD_ZERO_ANGLE_READ			0x012
#define HELIOS_NET_CMD_ZERO_ANGLE_WRITE			0x013
#define HELIOS_NET_CMD_CHANNEL_ANGLE_READ		0x014
#define HELIOS_NET_CMD_CHANNEL_ANGLE_WRITE		0x015
#define HELIOS_NET_CMD_MOTOR_UPDATE		    	0x016
#define HELIOS_NET_CMD_MOTOR_SEND				0x017
#define HELIOS_NET_CMD_MOTOR_RECV				0x018
#define HELIOS_NET_CMD_CODE_WHEEL_CALI         0x019
#define HELIOS_NET_CMD_INSPECTION              0x020
#define HELIOS_NET_CMD_CLEAR_BOT_CONFIG        0x021
#define HELIOS_NET_CMD_EYES_SAFE               0x022
#define HELIOS_NET_CMD_ENCODER_CURING          0x023
#define HELIOS_NET_CMD_WAVE_SHOW               0x024
#define HELIOS_NET_CMD_CODE_WHEEL_SAVE         0x025
#define HELIOS_NET_CMD_GET_MONITOR_PARAM       0x026
#define HELIOS_NET_CMD_SET_MODE                0X027
#define HELIOS_NET_CMD_GET_MODE                0X028
#define HELIOS_NET_CMD_REBOOT                  0X029
#define HELIOS_NET_CMD_CLEAR_RUNTIME_DATA      0x030
#define HELIOS_NET_CMD_GET_SW_BASE_CFG         0X031
#define HELIOS_NET_CMD_READ_BASE_CFG_JASON     0x032
#define HELIOS_NET_CMD_SW_BASE_CFG_UPDATE      0X033
#define HELIOS_NET_CMD_SW_BASE_CFG_VERSION     0X034
#define HELIOS_NET_CMD_SET_MOTOR_DIR           0X035
#define HELIOS_NET_CMD_GET_MOTOR_DIR           0X036
#define HELIOS_NET_CMD_READ_EVENT_LOG          0x037
#define HELIOS_NET_CMD_READ_MONITOR_LOG        0x038
#define HELIOS_NET_CMD_DELETE_EVENT_LOG        0x039
#define HELIOS_NET_CMD_RESTART_MONITOR_LOG     0x03A


      
#define HELIOS_NET_CMD_END                      0x050
       
#define HELIOS_NET_CMD_ACK_BEGIN                0x100
#define HELIOS_NET_CMD_ACK_READ_REGISTER        0x101
#define HELIOS_NET_CMD_ACK_WRITE_REGISTER       0x102
#define HELIOS_NET_CMD_ACK_TOP_BIN_UPDATE		0x103
#define HELIOS_NET_CMD_ACK_TOPBACKUP_UPDATE		0x104
#define HELIOS_NET_CMD_ACK_BOT_BIN_UPDATE		0x105
#define HELIOS_NET_CMD_ACK_BOTBACKUP_UPDATE		0x106
#define HELIOS_NET_CMD_ACK_LINUX_APP_UPDATE		0x107
#define HELIOS_NET_CMD_ACK_LAPPBACKUP_UPDATE	0x108
#define HELIOS_NET_CMD_ACK_READ_CONFIG			0x109
#define HELIOS_NET_CMD_ACK_WRITE_CONFIG			0x10A
#define HELIOS_NET_CMD_ACK_TOP_PARA_UPDATE		0x10B
#define HELIOS_NET_CMD_ACK_BOT_PARA_UPDATE		0x10C
#define HELIOS_NET_CMD_ACK_TOP_FLASH_READ		0x10D
#define HELIOS_NET_CMD_ACK_TOP_FLASH_WRITE		0x10E
#define HELIOS_NET_CMD_ACK_TOP_READ_REGISTER	0x10F
#define HELIOS_NET_CMD_ACK_TOP_WRITE_REGISTER	0x110
#define HELIOS_NET_CMD_ACK_TOP_GET_INTENSITY	0x111
#define HELIOS_NET_CMD_ACK_ZERO_ANGLE_READ		0x112
#define HELIOS_NET_CMD_ACK_ZERO_ANGLE_WRITE		0x113
#define HELIOS_NET_CMD_ACK_CHANNEL_ANGLE_READ	0x114
#define HELIOS_NET_CMD_ACK_CHANNEL_ANGLE_WRITE	0x115
#define HELIOS_NET_CMD_ACK_MOTOR_UPDATE	    	0x116
#define HELIOS_NET_CMD_ACK_MOTOR_SEND			0x117
#define HELIOS_NET_CMD_ACK_MOTOR_RECV			0x118
#define HELIOS_NET_CMD_ACK_WHEEL_CALI          0x119
#define HELIOS_NET_CMD_ACK_INSPECTION          0x120
#define HELIOS_NET_CMD_ACK_CLEAR_BOT_CONFIG    0x121
#define HELIOS_NET_CMD_ACK_EYES_SAFE           0x122
#define HELIOS_NET_CMD_ACK_ENCODER_CURING      0x123
#define HELIOS_NET_CMD_ACK_WAVE_SHOW           0x124
#define HELIOS_NET_CMD_ACK_CODE_WHEEL_SAVE     0x125
#define HELIOS_NET_CMD_ACK_GET_MONITOR_PARAM   0x126
#define HELIOS_NET_CMD_ACK_SET_MODE            0X127
#define HELIOS_NET_CMD_ACK_GET_MODE            0X128
#define HELIOS_NET_CMD_ACK_REBOOT              0x129
#define HELIOS_NET_CMD_ACK_GET_SW_BASE_CFG     0X131
#define HELIOS_NET_CMD_ACK_READ_BASE_CFG_JASON 0x132
#define HELIOS_NET_CMD_ACK_BASE_CFG_UPDATE     0X133
#define HELIOS_NET_CMD_ACK_BASE_CFG_VERSION    0X134
#define HELIOS_NET_CMD_ACK_SET_MOTOR_DIR       0X135
#define HELIOS_NET_CMD_ACK_GET_MOTOR_DIR       0X136
#define HELIOS_NET_CMD_ACK_READ_EVENT_LOG      0x137
#define HELIOS_NET_CMD_ACK_READ_MONITOR_LOG    0x138
#define HELIOS_NET_CMD_ACK_DELETE_EVENT_LOG    0x139
#define HELIOS_NET_CMD_ACK_RESTART_MONITOR_LOG 0x13A

#define HELIOS_NET_CMD_ACK_END                 0x150


#endif
